"use client";

import { useActionState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FRANCHISEE_STATUSES } from "@/lib/franchise";
import type { FormState } from "@/lib/validations/franchise";

type Values=Record<string,unknown>;
const initial:FormState={success:false,message:""};
export function FranchiseeForm({action,values={},cancelHref}:{action:(state:FormState,data:FormData)=>Promise<FormState>;values?:Values;cancelHref?:string}){const[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} className="grid gap-4 md:grid-cols-2"><Field name="companyName" label="Şirket Adı" value={values.companyName} required/><Field name="contactName" label="Yetkili Kişi" value={values.contactName} required/><Field name="phone" label="Telefon" value={values.phone} required/><Field name="whatsapp" label="WhatsApp" value={values.whatsapp}/><Field name="email" label="E-posta" type="email" value={values.email}/><Field name="taxNumber" label="Vergi Numarası" value={values.taxNumber}/><Field name="taxOffice" label="Vergi Dairesi" value={values.taxOffice}/><Field name="city" label="Şehir" value={values.city} required/><Field name="district" label="İlçe" value={values.district}/><label className="grid gap-2 text-sm font-medium"><span>Durum</span><select name="status" defaultValue={String(values.status??"SETUP")} className="h-10 rounded-lg border bg-[#f8faf6] px-3">{Object.entries(FRANCHISEE_STATUSES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><Field name="contractDate" label="Sözleşme Tarihi" type="date" value={dateValue(values.contractDate)}/><Field name="contractStartDate" label="Sözleşme Başlangıç" type="date" value={dateValue(values.contractStartDate)}/><Field name="contractEndDate" label="Sözleşme Bitiş" type="date" value={dateValue(values.contractEndDate)}/><Field name="defaultRoyaltyRate" label="Varsayılan Royalty Oranı (%)" type="number" value={values.defaultRoyaltyRate}/><Field name="marketingContributionRate" label="Pazarlama Katkı Oranı (%)" type="number" value={values.marketingContributionRate}/><label className="grid gap-2 text-sm font-medium md:col-span-2"><span>Adres</span><textarea name="address" defaultValue={String(values.address??"")} rows={3} className="rounded-lg border bg-[#f8faf6] p-3"/></label><label className="grid gap-2 text-sm font-medium md:col-span-2"><span>Genel Notlar</span><textarea name="generalNotes" defaultValue={String(values.generalNotes??"")} rows={4} className="rounded-lg border bg-[#f8faf6] p-3"/></label>{state.message&&<p className={`rounded-lg p-3 text-sm md:col-span-2 ${state.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{state.message}{state.success&&state.id&&<Link className="ml-2 font-semibold underline" href={`/franchisees/${state.id}`}>Bayi kaydını aç</Link>}</p>}<div className="flex justify-end gap-2 md:col-span-2">{cancelHref&&<Button asChild type="button" variant="outline"><Link href={cancelHref}>Vazgeç</Link></Button>}<Button disabled={pending} className="bg-[#17201b] text-white">{pending?"Kaydediliyor...":"Kaydet"}</Button></div></form>}
function Field({name,label,type="text",value,required=false}:{name:string;label:string;type?:string;value?:unknown;required?:boolean}){return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><input required={required} name={name} type={type} step={type==="number"?"0.01":undefined} min={type==="number"?0:undefined} max={type==="number"?100:undefined} defaultValue={String(value??"")} className="h-10 rounded-lg border bg-[#f8faf6] px-3"/></label>}
function dateValue(value:unknown){return value?new Date(String(value)).toISOString().slice(0,10):""}
