"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CalendarClock, MapPin, Search } from "lucide-react";
import { moveCandidate } from "@/app/pipeline/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/candidates";
import { isOpenTask, PIPELINE_STAGES } from "@/lib/pipeline";
import type { Candidate } from "@/types/candidate";

const ALL = "Tümü";
export function PipelineBoard({ candidates: initial }: { candidates: Candidate[] }) {
  const [candidates, setCandidates] = useState(initial); const [message, setMessage] = useState<{ok:boolean;text:string}|null>(null); const [pending,startTransition] = useTransition(); const router=useRouter();
  const [q,setQ]=useState(""); const [city,setCity]=useState(ALL); const [concept,setConcept]=useState(ALL); const [temperature,setTemperature]=useState(ALL); const [source,setSource]=useState(ALL); const [owner,setOwner]=useState(ALL); const [budget,setBudget]=useState(ALL); const [follow,setFollow]=useState(ALL); const [overdue,setOverdue]=useState(false); const [hot,setHot]=useState(false);
  const options=(key:keyof Candidate)=>Array.from(new Set(initial.map(c=>String(c[key])).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"tr"));
  const filtered=useMemo(()=>candidates.filter(c=>{const text=`${c.fullName} ${c.phone} ${c.city} ${c.email}`.toLocaleLowerCase("tr");const now=new Date();const next=c.nextFollowUpAt?new Date(c.nextFollowUpAt):null;const isLate=!!next&&next<now;const today=next&&next.toDateString()===now.toDateString();const week=next&&next>=now&&next.getTime()<=now.getTime()+7*86400000;return (!q||text.includes(q.toLocaleLowerCase("tr")))&&(city===ALL||c.city===city)&&(concept===ALL||c.interestedConcept===concept)&&(temperature===ALL||c.temperature===temperature)&&(source===ALL||c.source===source)&&(owner===ALL||c.assignedUserId===owner)&&(budget===ALL||c.investmentBudget===budget)&&(!overdue||isLate)&&(!hot||["Sıcak","Çok Sıcak"].includes(c.temperature))&&(follow===ALL||(follow==="Bugün"&&today)||(follow==="7 Gün"&&week)||(follow==="Gecikmiş"&&isLate));}),[candidates,q,city,concept,temperature,source,owner,budget,follow,overdue,hot]);
  function drop(id:string,status:string){const before=candidates;setCandidates(current=>current.map(c=>c.id===id?{...c,status}:c));startTransition(async()=>{const result=await moveCandidate(id,status);setMessage({ok:result.success,text:result.message});if(!result.success)setCandidates(before);else router.refresh();});}
  return <div className="space-y-4"><div className="rounded-lg border border-[#dfe4dc] bg-white p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="flex h-10 items-center gap-2 rounded-lg border bg-[#f8faf6] px-3 xl:col-span-2"><Search className="size-4"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ad, telefon, şehir veya e-posta ara" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><Filter value={city} set={setCity} items={options("city")} label="Şehir"/><Filter value={concept} set={setConcept} items={options("interestedConcept")} label="Konsept"/><Filter value={temperature} set={setTemperature} items={options("temperature")} label="Sıcaklık"/><Filter value={source} set={setSource} items={options("source")} label="Lead kaynağı"/><Filter value={owner} set={setOwner} items={options("assignedUserId")} label="Sorumlu"/><Filter value={budget} set={setBudget} items={options("investmentBudget")} label="Bütçe"/><Filter value={follow} set={setFollow} items={["Bugün","7 Gün","Gecikmiş"]} label="Takip tarihi"/><div className="flex flex-wrap gap-2"><Button type="button" variant={overdue?"default":"outline"} onClick={()=>setOverdue(!overdue)} className={overdue?"bg-rose-700 text-white":""}>Gecikmiş takipler</Button><Button type="button" variant={hot?"default":"outline"} onClick={()=>setHot(!hot)} className={hot?"bg-orange-600 text-white":""}>Sadece sıcak adaylar</Button></div></div></div>
  {message&&<div role="status" className={`rounded-lg p-3 text-sm ${message.ok?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{message.text}</div>}
  <div className={`flex gap-4 overflow-x-auto pb-4 ${pending?"opacity-80":""}`}>{PIPELINE_STAGES.map(stage=><section key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e.dataTransfer.getData("candidateId"),stage)} className="min-h-[420px] w-[310px] shrink-0 rounded-lg border border-[#dfe4dc] bg-[#eef1eb] p-3"><header className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">{stage}</h2><Badge variant="secondary">{filtered.filter(c=>c.status===stage).length}</Badge></header><div className="space-y-3">{filtered.filter(c=>c.status===stage).map(c=><PipelineCard key={c.id} candidate={c} onMove={drop}/>)}</div></section>)}</div></div>;
}
function PipelineCard({candidate:c,onMove}:{candidate:Candidate;onMove:(id:string,status:string)=>void}){const overdueTask=c.tasks.some(t=>isOpenTask(t.status)&&new Date(t.dueDate)<new Date());const lateFollow=!!c.nextFollowUpAt&&new Date(c.nextFollowUpAt)<new Date();return <article draggable onDragStart={e=>e.dataTransfer.setData("candidateId",c.id)} className="cursor-grab rounded-lg border border-[#dfe4dc] bg-white p-4 shadow-sm active:cursor-grabbing"><Link href={`/candidates/${c.id}`} className="font-semibold hover:underline">{c.fullName}</Link><p className="mt-1 flex items-center gap-1 text-xs text-[#65705f]"><MapPin className="size-3"/>{c.city} · {c.interestedConcept}</p><p className="mt-3 text-sm font-medium">{c.investmentBudget} {c.currency}</p><div className="mt-2 flex flex-wrap gap-1"><Badge className="bg-orange-100 text-orange-800">{c.temperature}</Badge><Badge variant="secondary">{c.source}</Badge></div><dl className="mt-3 grid gap-1 text-xs text-[#65705f]"><div><dt className="inline font-medium">Sorumlu: </dt><dd className="inline">{c.assignedUserId||"Atanmadı"}</dd></div><div><dt className="inline font-medium">Son görüşme: </dt><dd className="inline">{formatDate(c.lastContactAt)}</dd></div><div className={lateFollow?"font-semibold text-rose-700":""}><dt className="inline">Sonraki takip: </dt><dd className="inline">{formatDate(c.nextFollowUpAt)}</dd></div></dl>{(overdueTask||lateFollow)&&<p className="mt-3 flex items-center gap-1 rounded-md bg-rose-50 p-2 text-xs font-semibold text-rose-700"><AlertTriangle className="size-3.5"/>{overdueTask?"Gecikmiş görev":"Gecikmiş takip"}</p>} {!lateFollow&&c.nextFollowUpAt&&<p className="mt-2 flex items-center gap-1 text-xs text-[#65705f]"><CalendarClock className="size-3.5"/>Takip planlandı</p>}<select aria-label={`${c.fullName} aşamasını değiştir`} value={c.status} onChange={e=>onMove(c.id,e.target.value)} onPointerDown={e=>e.stopPropagation()} className="mt-3 h-8 w-full rounded-md border border-[#d3d9cf] bg-white px-2 text-xs">{PIPELINE_STAGES.map(stage=><option key={stage}>{stage}</option>)}</select></article>}
function Filter({value,set,items,label}:{value:string;set:(v:string)=>void;items:string[];label:string}){return <select aria-label={label} value={value} onChange={e=>set(e.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option>{ALL}</option>{items.map(i=><option key={i}>{i}</option>)}</select>}
