import{prisma}from"@/lib/prisma";import type{MetaLeadData,MetaField}from"./types";
export const normalizePhone=(value:string)=>{const digits=value.replace(/\D/g,"");return digits.startsWith("90")?digits.slice(2):digits.startsWith("0")?digits.slice(1):digits};
export const normalizeEmail=(value:string)=>value.trim().toLocaleLowerCase("tr-TR");
function field(fields:MetaField[]|undefined,...names:string[]){const wanted=names.map(x=>x.toLowerCase());return fields?.find(x=>wanted.includes(x.name.toLowerCase()))?.values?.[0]?.trim()||""}
function source(platform:string|undefined){const value=(platform||"").toLowerCase();return value.includes("instagram")||value==="ig"?"Instagram":"Facebook"}
function concept(value:string){const v=value.toLowerCase();if(v.includes("self"))return"Self Cafe";if(v.includes("corner"))return"Corner";return"Cafe"}
export async function syncMetaLead(data:MetaLeadData){
 const phone=field(data.field_data,"phone_number","phone","telefon"),email=field(data.field_data,"email","e-posta","eposta"),normalizedPhone=normalizePhone(phone),normalizedEmail=normalizeEmail(email),fullName=field(data.field_data,"full_name","name","ad_soyad","ad soyad")||"İsimsiz Meta Lead",city=field(data.field_data,"city","sehir","şehir")||"Belirtilmedi",requestedConcept=concept(field(data.field_data,"concept","requested_concept","konsept","talep_edilen_konsept")),leadSource=source(data.platform),leadDate=data.created_time?new Date(data.created_time):new Date();
 const exact=await prisma.lead.findUnique({where:{externalLeadId:data.id}});
 if(exact){await prisma.leadActivity.create({data:{leadId:exact.id,type:"Meta tekrar bildirimi",description:`${leadSource} tarafından aynı lead yeniden bildirildi; mükerrer kayıt açılmadı.`}});return{lead:exact,created:false,duplicate:true}}
 const direct=await prisma.lead.findMany({where:{OR:[...(normalizedPhone?[{normalizedPhone}]:[]),...(normalizedEmail?[{normalizedEmail}]:[]),...(phone?[{phone}]:[]),...(email?[{email}]:[])]}});
 let existing=direct.find(x=>(normalizedPhone&&normalizePhone(x.phone)===normalizedPhone)||(normalizedEmail&&normalizeEmail(x.email||"")===normalizedEmail));
 if(!existing&&(normalizedPhone||normalizedEmail)){const legacy=await prisma.lead.findMany({take:100,orderBy:{createdAt:"desc"}});existing=legacy.find(x=>(normalizedPhone&&normalizePhone(x.phone)===normalizedPhone)||(normalizedEmail&&normalizeEmail(x.email||"")===normalizedEmail))}
 if(existing){const lead=await prisma.lead.update({where:{id:existing.id},data:{fullName,phone:phone||existing.phone,email:email||existing.email,city:city==="Belirtilmedi"?existing.city:city,source:leadSource,requestedConcept,normalizedPhone:normalizedPhone||existing.normalizedPhone,normalizedEmail:normalizedEmail||existing.normalizedEmail,externalLeadId:data.id,metaFormId:data.form_id,metaPageId:data.page_id,activities:{create:{type:"Meta Lead güncellendi",description:`${leadSource} başvurusu telefon veya e-posta eşleşmesiyle mevcut lead kaydına işlendi.`}}}});return{lead,created:false,duplicate:false}}
 const lead=await prisma.lead.create({data:{fullName,phone:phone||"Belirtilmedi",email:email||null,city,source:leadSource,requestedConcept,status:"Yeni",leadDate,normalizedPhone:normalizedPhone||null,normalizedEmail:normalizedEmail||null,externalLeadId:data.id,metaFormId:data.form_id,metaPageId:data.page_id,activities:{create:{type:"Lead geldi",description:`${leadSource} Lead Ads formundan otomatik lead kaydı oluşturuldu.`}}}});return{lead,created:true,duplicate:false}
}
export async function integrationLog(status:string,eventType:string,message:string,externalId?:string,payload?:unknown){return prisma.integrationLog.create({data:{provider:"META",status,eventType,message,externalId,payload:payload?JSON.stringify(payload).slice(0,10000):null}})}
