"use client";

import { useActionState, useEffect, useState } from "react";
import { Check, Pencil, Plus, XCircle } from "lucide-react";
import { changeTaskStatus, createTask, updateTask } from "@/app/tasks/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/candidates";
import { isOpenTask, TASK_PRIORITIES, TASK_STATUSES, TEAM_MEMBERS } from "@/lib/pipeline";
import type { TaskActionState } from "@/lib/validations/task";
import type { CandidateTaskView } from "@/types/candidate";

const initial:TaskActionState={success:false,message:""};
export function CandidateTaskPanel({candidateId,tasks}:{candidateId:string;tasks:CandidateTaskView[]}){const[editing,setEditing]=useState<CandidateTaskView|null|undefined>(undefined);const[message,setMessage]=useState("");async function status(id:string,value:string){const result=await changeTaskStatus(id,value);setMessage(result.message);}return <div><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Aday Görevleri</h3><p className="text-sm text-[#65705f]">Takip aksiyonlarını planlayın ve sonuçlandırın.</p></div><Button onClick={()=>setEditing(null)} className="bg-[#17201b] text-white"><Plus className="size-4"/>Yeni Görev</Button></div>{message&&<p role="status" className="mb-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<div className="space-y-3">{tasks.map(t=>{const late=isOpenTask(t.status)&&new Date(t.dueDate)<new Date();return <div key={t.id} className={`rounded-lg border p-4 ${late?"border-rose-300 bg-rose-50":"border-[#edf0e9] bg-[#f8faf6]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge className={late?"bg-rose-700 text-white":"bg-[#17201b] text-white"}>{late?"Gecikmiş":t.status}</Badge><Badge variant="secondary">{t.priority}</Badge></div><h4 className="mt-3 font-semibold">{t.title}</h4><p className="mt-1 text-sm text-[#65705f]">{t.description}</p><p className={`mt-2 text-sm ${late?"font-semibold text-rose-700":""}`}>Bitiş: {formatDate(t.dueDate)} · Sorumlu: {t.assignedUserId||"Atanmadı"}</p></div><div className="flex gap-1"><Button size="icon" variant="outline" onClick={()=>setEditing(t)} aria-label="Görevi düzenle"><Pencil className="size-4"/></Button>{t.status!=="Tamamlandı"&&<Button size="icon" variant="outline" onClick={()=>status(t.id,"Tamamlandı")} aria-label="Görevi tamamla"><Check className="size-4"/></Button>}{t.status!=="İptal Edildi"&&<Button size="icon" variant="outline" onClick={()=>status(t.id,"İptal Edildi")} aria-label="Görevi iptal et"><XCircle className="size-4"/></Button>}</div></div></div>})}{tasks.length===0&&<p className="rounded-lg border border-dashed p-8 text-center text-sm text-[#65705f]">Henüz görev oluşturulmamış.</p>}</div>{editing!==undefined&&<TaskModal candidateId={candidateId} task={editing} close={()=>setEditing(undefined)}/>}</div>}
function TaskModal({candidateId,task,close}:{candidateId:string;task:CandidateTaskView|null;close:()=>void}){const action=task?updateTask.bind(null,task.id):createTask.bind(null,candidateId);const[state,formAction,pending]=useActionState(action,initial);useEffect(()=>{if(state.success){const timer=setTimeout(close,500);return()=>clearTimeout(timer)}},[state.success,close]);return <div className="fixed inset-0 z-50 flex items-end bg-[#17201b]/40 p-3 md:items-center md:justify-center"><form action={formAction} className="grid max-h-[90vh] w-full gap-4 overflow-auto rounded-lg bg-white p-5 md:max-w-xl"><h3 className="text-lg font-semibold">{task?"Görevi Düzenle":"Yeni Görev"}</h3><Field name="title" label="Başlık" value={task?.title}/><label className="grid gap-2"><span className="text-sm font-medium">Açıklama</span><textarea name="description" defaultValue={task?.description} rows={3} className="rounded-lg border bg-[#f8faf6] p-3"/></label><Field name="dueDate" label="Bitiş Tarihi" type="datetime-local" value={task?.dueDate.slice(0,16)}/><Select name="priority" label="Öncelik" items={[...TASK_PRIORITIES]} value={task?.priority}/><Select name="status" label="Durum" items={[...TASK_STATUSES]} value={task?.status}/><Select name="assignedUserId" label="Sorumlu Kişi" items={[...TEAM_MEMBERS]} value={task?.assignedUserId}/>{state.message&&<p className={`rounded-lg p-3 text-sm ${state.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{state.message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Vazgeç</Button><Button disabled={pending} className="bg-[#17201b] text-white">{pending?"Kaydediliyor...":"Kaydet"}</Button></div></form></div>}
function Field({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string}){return <label className="grid gap-2"><span className="text-sm font-medium">{label}</span><input required name={name} type={type} defaultValue={value} className="h-10 rounded-lg border bg-[#f8faf6] px-3"/></label>}
function Select({name,label,items,value}:{name:string;label:string;items:string[];value?:string}){return <label className="grid gap-2"><span className="text-sm font-medium">{label}</span><select name={name} defaultValue={value||items[0]} className="h-10 rounded-lg border bg-white px-3">{items.map(i=><option key={i}>{i}</option>)}</select></label>}
