"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{audit,requirePermission}from"@/lib/auth";import{approveOrder,changeOrderStatus,createInvoice,createOrder,prepareOrder,releaseOrder,shipOrder}from"@/lib/order-service";import{prisma}from"@/lib/prisma";import{productSchema}from"@/lib/validations/order";
export type ActionResult={ok:boolean;message:string};const paths=["/","/orders","/orders/admin","/warehouse/orders","/warehouse/stock","/warehouse/shipments","/warehouse/movements"];function refresh(){for(const path of paths)revalidatePath(path)}
export async function submitOrder(_s:ActionResult,fd:FormData):Promise<ActionResult>{try{await requirePermission("orders");const items=JSON.parse(String(fd.get("items")||"[]"));const order=await createOrder({franchiseeId:fd.get("franchiseeId"),branchId:fd.get("branchId")||undefined,warehouseId:fd.get("warehouseId"),requestedDeliveryDate:fd.get("requestedDeliveryDate")||undefined,notes:fd.get("notes")||undefined,items});refresh();return{ok:true,message:`${order.orderNumber} numaralı sipariş oluşturuldu.`}}catch(e){return{ok:false,message:e instanceof Error?e.message:"Sipariş oluşturulamadı."}}}
export async function orderCommand(id:string,command:string,fd?:FormData){const user=await requirePermission(command==="invoice"?"invoice":command==="ship"?"shipment_manage":"order_admin");if(command==="approve")await approveOrder(id);else if(command==="invoice")await createInvoice(id);else if(command==="queue")await changeOrderStatus(id,"WAREHOUSE_QUEUE");else if(command==="ready")await changeOrderStatus(id,"READY");else if(command==="reject")await releaseOrder(id,"REJECTED");else if(command==="cancel")await releaseOrder(id,"CANCELLED");else if(command==="ship")await shipOrder(id,String(fd?.get("carrierName")||""),String(fd?.get("trackingNumber")||""));await audit(command==="approve"?"ORDER_APPROVED":command==="invoice"?"INVOICE_CREATED":command==="ship"?"ORDER_SHIPPED":"ORDER_UPDATED","FranchiseOrder",id,`Sipariş işlemi: ${command}`,user.id);refresh()}
export async function savePreparation(id:string,fd:FormData){await requirePermission("warehouse");const ids=fd.getAll("itemId").map(String),prepared=fd.getAll("preparedQuantity").map(Number),missing=fd.getAll("missingQuantity").map(Number);await prepareOrder(id,ids.map((itemId,i)=>({id:itemId,preparedQuantity:prepared[i]||0,missingQuantity:missing[i]||0})));refresh()}
export async function createProduct(fd:FormData){await requirePermission("stock_manage");const data=productSchema.parse(Object.fromEntries(fd));await prisma.product.create({data:{...data,barcode:data.barcode||null}});refresh()}
export async function adjustStock(fd:FormData){const user=await requirePermission("stock_manage"),warehouseId=String(fd.get("warehouseId")),productId=String(fd.get("productId")),quantity=Number(fd.get("quantity"));if(quantity<0)throw new Error("Stok miktarı negatif olamaz.");await prisma.$transaction(async tx=>{const current=await tx.warehouseStock.findUnique({where:{warehouseId_productId:{warehouseId,productId}}});if(quantity<(current?.reservedQuantity??0))throw new Error("Stok, rezerve miktarın altına indirilemez.");await tx.warehouseStock.upsert({where:{warehouseId_productId:{warehouseId,productId}},create:{warehouseId,productId,quantity,availableQuantity:quantity},update:{quantity,availableQuantity:quantity-(current?.reservedQuantity??0)}});await tx.stockMovement.create({data:{warehouseId,productId,movementType:current?"ADJUSTMENT":"IN",quantity:Math.abs(quantity-(current?.quantity??0)),beforeQuantity:current?.quantity??0,afterQuantity:quantity,referenceType:"MANUAL",description:"Manuel stok güncellemesi."}})});await audit("STOCK_ADJUSTED","Product",productId,"Manuel stok düzeltmesi yapıldı.",user.id);refresh()}
export async function goToOrder(id:string){await requirePermission("warehouse");redirect(`/warehouse/orders/${id}`)}
