"use client";

import { useActionState, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, CheckSquare, MessageSquareText, Pencil, UserRound, X } from "lucide-react";
import { archiveCandidate, createInteraction, updateCandidate } from "@/app/candidates/actions";
import { CandidateForm } from "@/components/candidates/candidate-form";
import { CandidateTaskPanel } from "@/components/tasks/candidate-task-panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { formatDate } from "@/lib/candidates";
import type { ActionState } from "@/lib/validations/candidate";
import type { Candidate } from "@/types/candidate";

const initial: ActionState = { success: false, message: "" };
const interactionTypes = ["Telefon", "WhatsApp", "E-posta", "Online toplantı", "Yüz yüze toplantı", "Lokasyon ziyareti", "Diğer"];

export function CandidateDetailTabs({ candidate }: { candidate: Candidate }) {
  const [tab, setTab] = useState<"general"|"notes"|"tasks">("general"); const [edit, setEdit] = useState(false); const [note, setNote] = useState(false); const router = useRouter();
  const update = updateCandidate.bind(null, candidate.id);
  async function archive() { if (!window.confirm("Bu adayı arşivlemek istediğinize emin misiniz?")) return; const result = await archiveCandidate(candidate.id); if (result.success) router.push("/candidates"); else window.alert(result.message); }
  return <><Card className="rounded-lg border-[#dfe4dc] bg-white shadow-none"><CardHeader className="border-b border-[#edf0e9]"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2"><Button onClick={()=>setTab("general")} className={tab==="general"?"bg-[#17201b] text-white":"bg-[#f6f7f4] text-[#65705f]"}><UserRound className="size-4"/>Genel Bilgiler</Button><Button onClick={()=>setTab("notes")} className={tab==="notes"?"bg-[#17201b] text-white":"bg-[#f6f7f4] text-[#65705f]"}><MessageSquareText className="size-4"/>Görüşme Notları</Button><Button onClick={()=>setTab("tasks")} className={tab==="tasks"?"bg-[#17201b] text-white":"bg-[#f6f7f4] text-[#65705f]"}><CheckSquare className="size-4"/>Görevler</Button></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setEdit(true)}><Pencil className="size-4"/>Düzenle</Button><Button variant="outline" onClick={archive} className="text-rose-700"><Archive className="size-4"/>Arşivle</Button></div></div></CardHeader><CardContent className="p-5">{tab==="general"&&<General candidate={candidate}/>} {tab==="notes"&&<Timeline candidate={candidate} onAdd={()=>setNote(true)}/>} {tab==="tasks"&&<CandidateTaskPanel candidateId={candidate.id} tasks={candidate.tasks}/>}</CardContent></Card>
  {edit && <Modal title="Adayı Düzenle" onClose={()=>setEdit(false)}><CandidateForm candidate={candidate} action={update} onCancel={()=>setEdit(false)} onSuccess={()=>setEdit(false)}/></Modal>}
  {note && <Modal title="Yeni Görüşme Notu" onClose={()=>setNote(false)}><InteractionForm candidateId={candidate.id} onClose={()=>setNote(false)}/></Modal>}</>;
}
function General({candidate}:{candidate:Candidate}) { const fields = [["Ad Soyad",candidate.fullName],["Telefon",candidate.phone],["WhatsApp",candidate.whatsapp||"—"],["E-posta",candidate.email||"—"],["Konum",`${candidate.city} / ${candidate.district}`],["Ülke",candidate.country],["Yatırım Bütçesi",`${candidate.investmentBudget} ${candidate.currency}`],["Konsept",candidate.interestedConcept],["Durum",candidate.status],["Sıcaklık",candidate.temperature],["Son Görüşme",formatDate(candidate.lastContactAt)],["Sonraki Takip",formatDate(candidate.nextFollowUpAt)],["Kaynak",candidate.source],["Kayıp Nedeni",candidate.lostReason||"—"],["Genel Notlar",candidate.generalNotes||"—"]]; return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{fields.map(([l,v])=><div key={l} className="rounded-lg border border-[#edf0e9] bg-[#f8faf6] p-4"><p className="text-xs font-medium uppercase text-[#65705f]">{l}</p><p className="mt-2 text-sm font-semibold">{v}</p></div>)}</div>; }
function Timeline({candidate,onAdd}:{candidate:Candidate;onAdd:()=>void}) { return <div><div className="mb-5 flex items-center justify-between"><div><h3 className="font-semibold">Görüşme Zaman Çizelgesi</h3><p className="text-sm text-[#65705f]">En yeni görüşme en üstte gösterilir.</p></div><Button onClick={onAdd} className="bg-[#17201b] text-white">Yeni Not Ekle</Button></div><div className="space-y-3">{candidate.interactions.map(i=><div key={i.id} className="relative rounded-lg border border-[#edf0e9] bg-[#f8faf6] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><Badge className="bg-[#17201b] text-white">{i.interactionType}</Badge><strong>{i.title}</strong></div><time className="text-xs text-[#65705f]">{formatDate(i.interactionDate)}</time></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#364036]">{i.description}</p>{i.nextAction&&<p className="mt-3 text-sm"><strong>Sonraki aksiyon:</strong> {i.nextAction}</p>}{i.reminderAt&&<p className="mt-1 text-sm"><strong>Hatırlatma:</strong> {formatDate(i.reminderAt)}</p>}</div>)}{candidate.interactions.length===0&&<p className="rounded-lg border border-dashed p-8 text-center text-sm text-[#65705f]">Henüz görüşme notu eklenmemiş.</p>}</div></div>; }
function InteractionForm({candidateId,onClose}:{candidateId:string;onClose:()=>void}) { const action=createInteraction.bind(null,candidateId); const [state,formAction,pending]=useActionState(action,initial); return <form action={formAction} className="grid gap-4 p-5"><label className="grid gap-2"><span className="text-sm font-medium">Görüşme Türü</span><select name="interactionType" className="h-10 rounded-lg border px-3">{interactionTypes.map(i=><option key={i}>{i}</option>)}</select></label><Field name="title" label="Başlık"/><label className="grid gap-2"><span className="text-sm font-medium">Açıklama</span><textarea required name="description" rows={5} className="rounded-lg border bg-[#f8faf6] p-3"/></label><Field name="interactionDate" label="Görüşme Tarihi" type="datetime-local"/><Field name="nextAction" label="Sonraki Aksiyon"/><Field name="reminderAt" label="Hatırlatma Tarihi" type="datetime-local"/>{state.message&&<p className={`rounded-lg p-3 text-sm ${state.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{state.message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Vazgeç</Button><Button disabled={pending} className="bg-[#17201b] text-white">{pending?"Ekleniyor...":"Notu Ekle"}</Button></div></form>; }
function Field({name,label,type="text"}:{name:string;label:string;type?:string}) { return <label className="grid gap-2"><span className="text-sm font-medium">{label}</span><input required={name==="title"||name==="interactionDate"} name={name} type={type} className="h-10 rounded-lg border bg-[#f8faf6] px-3"/></label>; }
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-50 flex items-end bg-[#17201b]/40 p-3 backdrop-blur-sm md:items-center md:justify-center"><div className="max-h-[92vh] w-full overflow-auto rounded-lg bg-white md:max-w-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><h3 className="text-lg font-semibold">{title}</h3><Button size="icon" variant="ghost" onClick={onClose}><X className="size-4"/></Button></div>{children}</div></div>; }
