"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Filter, Plus, Search, X } from "lucide-react";
import { createCandidate } from "@/app/candidates/actions";
import { CandidateForm } from "@/components/candidates/candidate-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatDate } from "@/lib/candidates";
import type { Candidate } from "@/types/candidate";

const all = "Tümü";
export function CandidateList({ candidates }: { candidates: Candidate[] }) {
  const [query, setQuery] = useState(""); const [city, setCity] = useState(all); const [status, setStatus] = useState(all); const [concept, setConcept] = useState(all); const [temperature, setTemperature] = useState(all); const [open, setOpen] = useState(false);
  const values = (key: keyof Candidate) => Array.from(new Set(candidates.map(c => String(c[key])).filter(Boolean))).sort((a,b) => a.localeCompare(b,"tr"));
  const filtered = useMemo(() => candidates.filter(c => { const text = `${c.fullName} ${c.phone} ${c.email} ${c.city}`.toLocaleLowerCase("tr"); const q = query.trim().toLocaleLowerCase("tr"); return (!q || text.includes(q)) && (city === all || c.city === city) && (status === all || c.status === status) && (concept === all || c.interestedConcept === concept) && (temperature === all || c.temperature === temperature); }), [candidates, query, city, status, concept, temperature]);
  const reset = () => { setQuery(""); setCity(all); setStatus(all); setConcept(all); setTemperature(all); };
  return <div className="space-y-4"><Card className="rounded-lg border-[#dfe4dc] bg-white shadow-none"><CardHeader><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><CardTitle>Franchise Adayları</CardTitle><p className="mt-1 text-sm text-[#65705f]">{filtered.length} aday listeleniyor, toplam {candidates.length} aktif kayıt var.</p></div><Button onClick={() => setOpen(true)} className="bg-[#17201b] text-white"><Plus className="size-4" />Yeni Aday Ekle</Button></div></CardHeader><CardContent className="space-y-4">
    <div className="grid gap-3 xl:grid-cols-[1.3fr_repeat(4,0.8fr)_auto]"><label className="flex h-11 items-center gap-2 rounded-lg border border-[#d3d9cf] bg-[#f8faf6] px-3"><Search className="size-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="İsim, telefon, e-posta veya şehir ara" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><Select value={city} set={setCity} items={values("city")}/><Select value={status} set={setStatus} items={values("status")}/><Select value={concept} set={setConcept} items={values("interestedConcept")}/><Select value={temperature} set={setTemperature} items={values("temperature")}/><Button variant="outline" onClick={reset}><Filter className="size-4"/>Sıfırla</Button></div>
    <div className="overflow-x-auto rounded-lg border border-[#dfe4dc]"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-[#f6f7f4] text-xs uppercase text-[#65705f]"><tr>{["Ad Soyad","Telefon","E-posta","Şehir","Yatırım Bütçesi","Konsept","Durum","Sıcaklık","Son Görüşme","Sonraki Takip"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-[#edf0e9]">{filtered.map(c=><tr key={c.id} className="hover:bg-[#fbfcf9]"><td className="px-4 py-4"><Link href={`/candidates/${c.id}`} className="font-semibold hover:underline">{c.fullName}</Link><div className="text-xs text-[#65705f]">{c.source}</div></td><td className="px-4">{c.phone}</td><td className="px-4">{c.email || "—"}</td><td className="px-4">{c.city}<div className="text-xs text-[#65705f]">{c.district}</div></td><td className="px-4">{c.investmentBudget} {c.currency}</td><td className="px-4">{c.interestedConcept}</td><td className="px-4"><Badge className="bg-[#ecfbdc] text-[#2f5f20]">{c.status}</Badge></td><td className="px-4"><Badge className="bg-rose-100 text-rose-800">{c.temperature}</Badge></td><td className="px-4">{formatDate(c.lastContactAt)}</td><td className="px-4">{formatDate(c.nextFollowUpAt)}</td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-sm text-[#65705f]">Filtrelere uygun aday bulunamadı.</p>}</div>
  </CardContent></Card>{open && <div className="fixed inset-0 z-50 flex items-end bg-[#17201b]/40 p-3 backdrop-blur-sm md:items-center md:justify-center"><div className="max-h-[92vh] w-full overflow-auto rounded-lg bg-white md:max-w-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><div><h3 className="text-lg font-semibold">Yeni Aday Ekle</h3><p className="text-sm text-[#65705f]">Franchise adayını kalıcı olarak kaydet.</p></div><Button size="icon" variant="ghost" onClick={()=>setOpen(false)}><X className="size-4"/></Button></div><CandidateForm action={createCandidate} onCancel={()=>setOpen(false)} onSuccess={()=>setOpen(false)}/></div></div>}</div>;
}
function Select({value,set,items}:{value:string;set:(v:string)=>void;items:string[]}) { return <select value={value} onChange={e=>set(e.target.value)} className="h-11 rounded-lg border border-[#d3d9cf] bg-white px-3 text-sm"><option>{all}</option>{items.map(i=><option key={i}>{i}</option>)}</select>; }
