"use client";
import { useActionState, useEffect } from "react";
import { createLead } from "@/app/leads/actions";
import { Button } from "@/components/ui/button";
import { LEAD_CONCEPTS, LEAD_SOURCES } from "@/lib/leads";
import type { LeadActionState } from "@/lib/validations/lead";
const initial:LeadActionState={success:false,message:""};
export function LeadForm({onSuccess,onCancel}:{onSuccess:()=>void;onCancel:()=>void}){const[state,action,pending]=useActionState(createLead,initial);useEffect(()=>{if(state.success){const timer=setTimeout(onSuccess,500);return()=>clearTimeout(timer)}},[state.success,onSuccess]);return <form action={action} className="grid gap-4 p-5 md:grid-cols-2"><Field name="fullName" label="Ad Soyad" error={state.errors?.fullName}/><Field name="phone" label="Telefon" error={state.errors?.phone}/><Field name="email" label="E-posta" type="email" error={state.errors?.email}/><Field name="city" label="Şehir" error={state.errors?.city}/><Select name="source" label="Kaynak" items={[...LEAD_SOURCES]}/><Select name="requestedConcept" label="Talep Edilen Konsept" items={[...LEAD_CONCEPTS]}/>{state.message&&<p className={`md:col-span-2 rounded-lg p-3 text-sm ${state.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{state.message}</p>}<div className="flex justify-end gap-2 border-t pt-4 md:col-span-2"><Button type="button" variant="outline" onClick={onCancel}>Vazgeç</Button><Button type="submit" disabled={pending} className="bg-[#17201b] text-white">{pending?"Kaydediliyor...":"Lead'i Kaydet"}</Button></div></form>}
function Field({name,label,type="text",error}:{name:string;label:string;type?:string;error?:string[]}){return <label className="grid gap-2"><span className="text-sm font-medium">{label}</span><input required={name!=="email"} name={name} type={type} className="h-10 rounded-lg border bg-[#f8faf6] px-3"/>{error?.[0]&&<span className="text-xs text-rose-700">{error[0]}</span>}</label>}
function Select({name,label,items}:{name:string;label:string;items:string[]}){return <label className="grid gap-2"><span className="text-sm font-medium">{label}</span><select name={name} className="h-10 rounded-lg border bg-white px-3">{items.map(i=><option key={i}>{i}</option>)}</select></label>}
