"use client";
import Link from "next/link";
import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, CheckCircle2, Clock3, Phone, Send } from "lucide-react";
import { addLeadActivity } from "@/app/leads/actions";
import { changeLeadStatusForm, convertLeadForm } from "@/app/leads/form-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/candidates";
import { LEAD_ACTIVITY_TYPES, LEAD_STATUSES, type LeadView } from "@/lib/leads";
import type { LeadActionState } from "@/lib/validations/lead";
const initial:LeadActionState={success:false,message:""};
export function LeadDetail({lead}:{lead:LeadView}){
 const router=useRouter();
 const[state,activityAction,activityPending]=useActionState(addLeadActivity.bind(null,lead.id),initial);
 const[statusState,statusAction,statusPending]=useActionState(changeLeadStatusForm.bind(null,lead.id),initial);
 const[convertState,convertAction,convertPending]=useActionState(convertLeadForm.bind(null,lead.id),initial);
 useEffect(()=>{if(convertState.success&&convertState.candidateId)router.push(`/candidates/${convertState.candidateId}`)},[convertState,router]);
 return <div className="grid gap-4 xl:grid-cols-[1fr_0.72fr]"><div className="space-y-4">
  <div className="rounded-lg border border-[#dfe4dc] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex gap-2"><Badge className="bg-sky-100 text-sky-700">{lead.status}</Badge><Badge variant="secondary">{lead.source}</Badge></div><h2 className="mt-4 text-2xl font-semibold">{lead.fullName}</h2><p className="mt-1 text-sm text-[#65705f]">{lead.city} · {lead.requestedConcept}</p></div>{lead.convertedCandidateId?<Link href={`/candidates/${lead.convertedCandidateId}`} className="inline-flex h-9 items-center gap-2 rounded-lg bg-emerald-100 px-3 text-sm font-medium text-emerald-700"><CheckCircle2 className="size-4"/>Adayı Aç</Link>:<form action={convertAction}><Button type="submit" disabled={convertPending} className="bg-[#17201b] text-white">Franchise Adayına Dönüştür<ArrowRight className="size-4"/></Button></form>}</div>{convertState.message&&<p role="status" className={`mt-4 rounded-lg p-3 text-sm ${convertState.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{convertState.message}</p>}<div className="mt-5 grid gap-3 md:grid-cols-2"><Info label="Telefon" value={lead.phone}/><Info label="E-posta" value={lead.email||"—"}/><Info label="Şehir" value={lead.city}/><Info label="Lead Tarihi" value={formatDate(lead.leadDate)}/><Info label="Kaynak" value={lead.source}/><Info label="Talep Edilen Konsept" value={lead.requestedConcept}/></div></div>
  <form action={statusAction} className="rounded-lg border border-[#dfe4dc] bg-white p-5"><h3 className="font-semibold">Lead Durumu</h3><p className="mt-1 text-sm text-[#65705f]">İnceleme sürecindeki güncel aşamayı seçin.</p><div className="mt-4 flex gap-2"><select aria-label="Lead durumu" name="status" defaultValue={lead.status} disabled={!!lead.convertedCandidateId} className="h-10 min-w-0 flex-1 rounded-lg border bg-white px-3 text-sm">{LEAD_STATUSES.map(i=><option key={i}>{i}</option>)}</select><Button type="submit" disabled={statusPending||!!lead.convertedCandidateId} className="bg-[#17201b] text-white">Durumu Kaydet</Button></div>{statusState.message&&<p className={`mt-3 rounded-lg p-3 text-sm ${statusState.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{statusState.message}</p>}</form>
  <form action={activityAction} className="rounded-lg border border-[#dfe4dc] bg-white p-5"><h3 className="font-semibold">Aktivite Ekle</h3><div className="mt-4 grid gap-3"><select aria-label="Aktivite türü" name="type" className="h-10 rounded-lg border px-3 text-sm">{LEAD_ACTIVITY_TYPES.map(i=><option key={i}>{i}</option>)}</select><textarea aria-label="Aktivite açıklaması" required name="description" rows={4} placeholder="Görüşme veya not detayını yazın" className="rounded-lg border bg-[#f8faf6] p-3 text-sm"/>{state.message&&<p className={`rounded-lg p-3 text-sm ${state.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{state.message}</p>}<Button type="submit" disabled={activityPending} className="justify-self-end bg-[#17201b] text-white"><Send className="size-4"/>{activityPending?"Kaydediliyor...":"Aktiviteyi Kaydet"}</Button></div></form>
 </div><aside className="rounded-lg border border-[#dfe4dc] bg-white p-5"><div className="mb-5"><h3 className="font-semibold">Zaman Çizelgesi</h3><p className="mt-1 text-sm text-[#65705f]">En yeni aktivite en üstte gösterilir.</p></div><div className="relative space-y-4 before:absolute before:bottom-3 before:left-[15px] before:top-3 before:w-px before:bg-[#dfe4dc]">{lead.activities.map(a=><div key={a.id} className="relative flex gap-3"><div className="z-10 flex size-8 shrink-0 items-center justify-center rounded-full bg-[#17201b] text-[#a8ff60]">{a.type==="Telefon edildi"?<Phone className="size-4"/>:<Clock3 className="size-4"/>}</div><div className="min-w-0 flex-1 rounded-lg bg-[#f8faf6] p-3"><p className="text-sm font-semibold">{a.type}</p><p className="mt-1 text-sm leading-6 text-[#65705f]">{a.description}</p><time className="mt-2 block text-xs text-[#8a9484]">{formatDate(a.createdAt)}</time></div></div>)}</div></aside></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-[#edf0e9] bg-[#f8faf6] p-4"><p className="text-xs font-medium uppercase text-[#65705f]">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
