export const INTEGRATION_PROVIDERS = {
  TICIMAX: "TICIMAX",
  PARASUT: "PARASUT",
} as const;

export const INTEGRATION_STATUSES = {
  RECEIVED: "RECEIVED",
  PROCESSING: "PROCESSING",
  SUCCESS: "SUCCESS",
  RETRY_PENDING: "RETRY_PENDING",
  FAILED: "FAILED",
  IGNORED: "IGNORED",
  MANUAL_REVIEW: "MANUAL_REVIEW",
  CANCELLED: "CANCELLED",
} as const;

export const INTEGRATION_DIRECTIONS = {
  INBOUND: "INBOUND",
  OUTBOUND: "OUTBOUND",
} as const;

export const INTEGRATION_ERROR_CODES = {
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  RATE_LIMIT: "RATE_LIMIT",
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT: "TIMEOUT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  PRODUCT_MAPPING_ERROR: "PRODUCT_MAPPING_ERROR",
  BRANCH_MAPPING_ERROR: "BRANCH_MAPPING_ERROR",
  CUSTOMER_MAPPING_ERROR: "CUSTOMER_MAPPING_ERROR",
  SUPPLIER_MAPPING_ERROR: "SUPPLIER_MAPPING_ERROR",
  CURRENCY_ERROR: "CURRENCY_ERROR",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  DUPLICATE_EVENT: "DUPLICATE_EVENT",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export const ORDER_FINANCIAL_STATUSES = {
  INVOICE_NOT_REQUIRED: "INVOICE_NOT_REQUIRED",
  INVOICE_PENDING: "INVOICE_PENDING",
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_MATCHED: "INVOICE_MATCHED",
  INVOICE_MISMATCH: "INVOICE_MISMATCH",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",
  INVOICE_FAILED: "INVOICE_FAILED",
} as const;

export const RECONCILIATION_STATUSES = {
  MATCHED: "MATCHED",
  PARTIALLY_MATCHED: "PARTIALLY_MATCHED",
  AMOUNT_MISMATCH: "AMOUNT_MISMATCH",
  PRODUCT_MISMATCH: "PRODUCT_MISMATCH",
  CUSTOMER_MISMATCH: "CUSTOMER_MISMATCH",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  INVOICE_MISSING: "INVOICE_MISSING",
  ORDER_MISSING: "ORDER_MISSING",
  MANUAL_REVIEW: "MANUAL_REVIEW",
  RESOLVED: "RESOLVED",
} as const;

export const MANUAL_REVIEW_REASONS = {
  BRANCH_MAPPING_REQUIRED: "Şube Eşleştirme Bekliyor",
  PRODUCT_MAPPING_REQUIRED: "Ürün Eşleştirme Bekliyor",
  CUSTOMER_MAPPING_REQUIRED: "Müşteri Eşleştirme Bekliyor",
  SUPPLIER_MAPPING_REQUIRED: "Tedarikçi Eşleştirme Bekliyor",
  INVOICE_MATCH_REQUIRED: "Fatura Eşleştirme Bekliyor",
  ORDER_CHANGE_REVIEW: "Sipariş Değişiklik İncelemesi",
} as const;
