"use client";

import { useActionState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { BRANCH_CONCEPTS, BRANCH_STATUSES, LOCATION_TYPES } from "@/lib/franchise";
import type { FormState } from "@/lib/validations/franchise";

type Values=Record<string,unknown>;type Owner={id:string;companyName:string};const initial:FormState={success:false,message:""};
export function BranchForm({action,owners,values={},fixedOwnerId,cancelHref}:{action:(state:FormState,data:FormData)=>Promise<FormState>;owners:Owner[];values?:Values;fixedOwnerId?:string;cancelHref?:string}){const[state,formAction,pending]=useActionState(action,initial);return <form action={formAction} className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium"><span>Bağlı Bayi</span><select name="franchiseeId" defaultValue={fixedOwnerId??String(values.franchiseeId??"")} disabled={Boolean(fixedOwnerId)} className="h-10 rounded-lg border bg-[#f8faf6] px-3"><option value="">Bayi seçin</option>{owners.map(o=><option key={o.id} value={o.id}>{o.companyName}</option>)}</select>{fixedOwnerId&&<input type="hidden" name="franchiseeId" value={fixedOwnerId}/>}</label><Field name="branchName" label="Şube Adı" value={values.branchName} required/><Field name="city" label="Şehir" value={values.city} required/><Field name="district" label="İlçe" value={values.district}/><Select name="concept" label="Konsept" value={String(values.concept??"CORNER")} options={BRANCH_CONCEPTS}/><Select name="locationType" label="Lokasyon Tipi" value={String(values.locationType??"STREET")} options={LOCATION_TYPES}/><Select name="status" label="Durum" value={String(values.status??"PLANNED")} options={BRANCH_STATUSES}/><Field name="operationsManager" label="Operasyon Sorumlusu" value={values.operationsManager}/><Field name="plannedOpeningDate" label="Planlanan Açılış" type="date" value={dateValue(values.plannedOpeningDate)}/><Field name="openingDate" label="Gerçek Açılış" type="date" value={dateValue(values.openingDate)}/><Field name="royaltyRate" label="Royalty Oranı (%)" type="number" value={values.royaltyRate}/><Field name="marketingContributionRate" label="Pazarlama Katkı Oranı (%)" type="number" value={values.marketingContributionRate}/><label className="grid gap-2 text-sm font-medium md:col-span-2"><span>Adres</span><textarea name="address" defaultValue={String(values.address??"")} rows={3} className="rounded-lg border bg-[#f8faf6] p-3"/></label><label className="grid gap-2 text-sm font-medium md:col-span-2"><span>Genel Notlar</span><textarea name="generalNotes" defaultValue={String(values.generalNotes??"")} rows={3} className="rounded-lg border bg-[#f8faf6] p-3"/></label>{state.message&&<p className={`rounded-lg p-3 text-sm md:col-span-2 ${state.success?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{state.message}{state.success&&state.id&&<Link className="ml-2 font-semibold underline" href={`/branches/${state.id}`}>Şube kaydını aç</Link>}</p>}<div className="flex justify-end gap-2 md:col-span-2">{cancelHref&&<Button asChild type="button" variant="outline"><Link href={cancelHref}>Vazgeç</Link></Button>}<Button disabled={pending} className="bg-[#17201b] text-white">{pending?"Kaydediliyor...":"Kaydet"}</Button></div></form>}
function Field({name,label,type="text",value,required=false}:{name:string;label:string;type?:string;value?:unknown;required?:boolean}){return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><input required={required} name={name} type={type} step={type==="number"?"0.01":undefined} min={type==="number"?0:undefined} max={type==="number"?100:undefined} defaultValue={String(value??"")} className="h-10 rounded-lg border bg-[#f8faf6] px-3"/></label>}
function Select({name,label,value,options}:{name:string;label:string;value:string;options:Record<string,string>}){return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><select name={name} defaultValue={value} className="h-10 rounded-lg border bg-[#f8faf6] px-3">{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function dateValue(value:unknown){return value?new Date(String(value)).toISOString().slice(0,10):""}
